#!/usr/bin/expect -f
set timeout -1
spawn scp -o StrictHostKeyChecking=no /Users/hisoka/flutter_apps/food\ safety/backend/remote_deploy.sh root@170.64.175.81:/tmp/remote_deploy.sh
expect "password:"
send "OnePiece@2026!\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no root@170.64.175.81
expect "password:"
send "OnePiece@2026!\r"
expect "#"
send "bash /tmp/remote_deploy.sh\r"
expect "#"
send "exit\r"
expect eof
